### ISSUE TITLE
Add custom baud rate for CRSF protocol

### ISSUE THREAD

**Issue by krababonga** [ZZ-Cat/CRSFforArduino#131]
### Is there already an issue for this?

- [X] I have searched the issues and there is no existing issue for this feature request.

### Is your feature request related to a problem?

Library won't work on new tracer receivers due to wrong baud rate. Please take a look at betaflight source code:
https://github.com/betaflight/betaflight/blob/master/src/main/rx/crsf_protocol.h#L34

### Describe the solution you'd like

Set custom crsf baud rate in constructor.

### Describe alternatives you've considered

Currently I changed value in library constant and it works for me.

**Comment by ZZ-Cat** [comment]
Sweet as. By rights, this should be doable.  
At this stage, I'll put this in the next maintenance release to v1.0.x, so it will get released faster and won't get bogged down with the other stuff I have going on with #111.
