### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by mrRobot62** [ZZ-Cat/CRSFforArduino#38]
### Minimum requirements

- [X] Core clock speed is 48 MHz or faster?
- [X] Is the CPU an ARM Cortex M0+ or later?
- [X] Is the host microcontroller's UART peripheral able to support 420,000 (or higher) baud rate(s)?
- [X] Is your development board currently supported in the Arduino IDE?

### What development board would you like me to add?

It would be very helpful to have running version based on ESP32-DEV (like a WROOM)

Tensilica Xtensa LX6
32 bit Dual-Core @ 160 / 240Mhz

Most time a lot of libraries are compatible to ESP32 devices

**Comment by ZZ-Cat** [comment]
Abso-fricken-lutely! =^/,..,^=

I am aware that someone made a [fork](https://github.com/ppetermann/CRSFforArduino) of my project, where they are trying their hand at adding in ESP32 support. They have bet me to the punch on this, as I was already planning to do this after #37 is merged. I may get in touch with them, and see if they are willing to submit their additions as a Pull Request to my project.

I also know that literally every ExpressLRS transmitter module and receiver in existence is either ESP32 or ESP8285, and ExpressLRS themselves recently [added support](https://github.com/ExpressLRS/ExpressLRS/pull/2410) for the ESP32-S3.
